parameters:
    livechat.chattranscript.entity.class:            Aligent\LiveChatBundle\Entity\ChatTranscript
    livechat.chattranscript.activity.manager.class:  Aligent\LiveChatBundle\Entity\Manager\ChatTranscriptManager
    livechat.activity_list.provider.class:           Aligent\LiveChatBundle\Provider\ChatActivityListProvider
    livechat.listener.config_listener.class:         Aligent\LiveChatBundle\EventListener\ConfigListener
    livechat.guzzle.class:                           Guzzle\Http\Client
    livechat.api_client_visitor.class:               Aligent\LiveChatBundle\Service\API\Client\Visitor
    livechat.webhook_chatstart.class:                Aligent\LiveChatBundle\Service\Webhook\ChatStart
    livechat.webhook_chatend.class:                  Aligent\LiveChatBundle\Service\Webhook\ChatEnd
    livechat.webhook_transcriptparser.class:         Aligent\LiveChatBundle\Service\Webhook\TranscriptParser
    livechat.repository.contact.class:               Aligent\LiveChatBundle\Entity\Repository\ContactRepository
    livechat.repository.user:                        Aligent\LiveChatBundle\Entity\Repository\UserRepository
    livechat.security.encoder.bcrypt.cost: 10

services:
    livechat.guzzle:
        class: '%livechat.guzzle.class%'

    livechat.security.encoder.bcrypt:
        class: '%security.encoder.bcrypt.class%'
        arguments: ['%livechat.security.encoder.bcrypt.cost%']

    livechat.api_client_visitor:
        class: '%livechat.api_client_visitor.class%'
        arguments:
          - '@logger'
          - '@serializer.encoder.json'
          - '@livechat.guzzle'
          - '@router'
          - '@translator.default'

    livechat.webhook_chatstart:
        class: '%livechat.webhook_chatstart.class%'
        arguments:
          - '@logger'
          - '@serializer.encoder.json'
          - '@livechat.repository.contact'
          - '@livechat.api_client_visitor'

    livechat.webhook_chatend:
        class: '%livechat.webhook_chatend.class%'
        arguments:
          - '@logger'
          - '@serializer.encoder.json'
          - '@livechat.repository.contact'
          - "@livechat.webhook_transcriptparser"
          - '@livechat.repository.user'
          - "@doctrine.orm.entity_manager"
          - "@oro_activity.manager"

    livechat.webhook_transcriptparser:
        class: '%livechat.webhook_transcriptparser.class%'
        arguments: ['@logger', '@serializer.encoder.json']

    livechat.repository.contact:
        class: '%livechat.repository.contact.class%'
        arguments:
            - '@oro_contact.contact.manager'

    livechat.repository.user:
        class: '%livechat.repository.user%'
        arguments:
            - '@oro_user.manager'

    livechat.chattranscript.activity.manager:
        class: '%livechat.chattranscript.activity.manager.class%'
        arguments:
            - "@oro_activity.manager"

    livechat.activity_list.provider:
        class: '%livechat.activity_list.provider.class%'
        arguments:
           - "@oro_entity.doctrine_helper"
           - "@oro_security.owner.entity_owner_accessor.link"
           - "@oro_activity.association_helper"
           - "@oro_comment.association_helper"
           - "@livechat.webhook_transcriptparser"
        tags:
           - {name: oro_activity_list.provider, priority: 10 }

    livechat.listener.system_config:
      class: '%livechat.listener.config_listener.class%'
      arguments:
        - "@livechat.security.encoder.bcrypt"
      tags:
        - { name: kernel.event_listener, event: oro_config.settings_before_save, method: onBeforeSave }